Updated the changes and  Homework
chindhur/Airport-project pull request #1
Opened 2023-04-24 17:46 UTC by chindhur

Interfaces , and polymorphism

2023-04-24 18:02 UTC, ankochergin commented on src/com/airport/Airport.java
> +    private Boolean mIsOpen = true;
why some of your variables names starts with `m`?

2023-04-24 18:02 UTC, ankochergin commented on src/com/airport/AirportEmployee.java
> +    Airport mAirport = null;
I think Airport should contain list of employees, not Employee contains Airport

2023-04-24 18:02 UTC, ankochergin commented on src/com/airport/AirportRunway.java
> +    }
```suggestion
public class AirportRunway implements Runway {

    private String runwayNumber;
    private String flightName;
    private Boolean mIsoccupied = false;
    
    public String getRunwayNumber() {
        return runwayNumber;
    }
    
    public void setRunwayNumber(String runwayNumber) {
        this.runwayNumber = runwayNumber;
    }
    
    public String getFlightName() {
        return flightName;
    }
```

2023-04-24 18:02 UTC, ankochergin commented on src/com/airport/AirportRunway.java
> +    }
please check formatting in all classes

2023-04-24 18:02 UTC, ankochergin commented on src/com/airport/metalDetecterCheck.java
> +public class metalDetecterCheck implements SecurityCheck {
class name should start with uppercase letter

2023-04-24 18:02 UTC, ankochergin commented on src/com/airport/Luggage.java
> +        }
overcomplicated solution

2023-04-24 18:02 UTC, ankochergin commented on src/com/airport/Luggage.java
> +        }
```suggestion
    public Boolean hasMetalObject() {
        return items.contains("metal");
    }
```

2023-04-24 18:02 UTC, ankochergin commented on src/com/airport/Luggage.java
> +        }
the same for second similar `if`

2023-04-24 18:02 UTC, ankochergin commented on src/com/airport/Passenger.java
>      Luggage luggage;
always specify access modifies explicitly

2023-04-24 18:02 UTC, ankochergin commented on src/com/airport/Route.java
> +public interface Route {
it's recommended to start interface name with I, for example Route here

2023-04-24 18:02 UTC, ankochergin commented on src/com/impl/airport/Emirates.java
> +public class Emirates extends Flight  {
be consistent in naming, add Airlines to the name as for other classes

2023-04-24 18:02 UTC, ankochergin commented on src/com/impl/airport/Emirates.java
> +        super.setFlightName("Emirates Airlines");
```suggestion
    static{
        Printer.print("Have a Nice and Happy Journey with Emirates");
    }
    
    public Emirates() {
        super.setFlightName("Emirates Airlines");
```

2023-04-24 18:02 UTC, ankochergin commented on src/com/impl/airport/route/SFORoute.java
> +}
all route classes are just code duplication, we can have 1 class for all flights

2023-04-24 18:02 UTC, ankochergin commented on src/com/person/Address.java
> -
empty lines should be between each method

2023-04-25 18:51 UTC, chindhur commented on src/com/impl/airport/route/SFORoute.java
> +}
removed TokyoRoute and SingaporeRoute and implemented only SFORoute for IRoute interface.

2023-04-25 18:51 UTC, chindhur commented on src/com/person/Address.java
> -
added empty lines between methods

2023-04-25 18:52 UTC, chindhur commented on src/com/airport/Airport.java
> +    private Boolean mIsOpen = true;
changed the variables with appropriate names.

2023-04-25 18:52 UTC, chindhur commented on src/com/airport/AirportEmployee.java
> +    Airport mAirport = null;
Made the changes as suggested.

2023-04-25 18:52 UTC, chindhur commented on src/com/airport/AirportRunway.java
> +    }
formatting done as suggested.

2023-04-25 18:53 UTC, chindhur commented on src/com/airport/metalDetecterCheck.java
> +public class metalDetecterCheck implements SecurityCheck {
Changed the class name.

2023-04-25 18:53 UTC, chindhur commented on src/com/airport/Luggage.java
> +        }
changed the solution as given in suggested changes.

2023-04-25 18:54 UTC, chindhur commented on src/com/airport/Route.java
> +public interface Route {
Changed the interface names accordingly

2023-04-25 18:54 UTC, chindhur commented on src/com/impl/airport/Emirates.java
> +public class Emirates extends Flight  {
changed the naming accordingly.

2023-04-25 18:57 UTC, chindhur commented on src/com/impl/airport/Emirates.java
> +        super.setFlightName("Emirates Airlines");
added space in static block as suggested.

2023-04-25 18:59 UTC, chindhur commented
Hi Andrey,
I have updated all the changes suggested for the homework .Please check

2023-04-26 09:51 UTC, ankochergin requested changes

2023-04-26 09:51 UTC, ankochergin commented on src/com/airport/Airport.java
> +    private Boolean IsRunwayOPen = true;
```suggestion
    private Boolean isRunwayOpen = true;
```

2023-04-26 09:51 UTC, ankochergin commented on src/com/airport/Airport.java
> +    private Boolean IsRunwayOPen = true;
variable name should start with lowercase letter

2023-04-26 09:51 UTC, ankochergin commented on src/com/airport/Flight.java
> +    }
```suggestion
    static {
        noOfWings = 2;
        Printer.print("Initialized number of wings in static block");
    }
```

2023-04-26 09:51 UTC, ankochergin commented on src/com/airport/Flight.java
> +    }
+ put static block after variables
all variables (fields) should be in one place

2023-04-26 09:51 UTC, ankochergin commented on src/com/airport/MetalDetectorCheck.java
> +}
```suggestion
public class MetalDetectorCheck implements ISecurityCheck {

    private Boolean isThreatDetected;
    
    @Override
    public void scanForSecurity(Passenger passenger) {
        if (passenger.hasMetalObject()) {
            Printer.print("Metal detected with this passenger");
            isThreatDetected = true;
        }
    }

    public void scanForSecurity(Luggage luggage) {
        if (luggage.hasMetalObject()) {
            Printer.print("Metal detected with Luggage" + luggage.getLuggageId());
            isThreatDetected = true;
        }
    }

    public Boolean isThreatDetected() {
        return isThreatDetected;
    }
}
```

2023-04-26 09:51 UTC, ankochergin commented on src/com/airport/Passenger.java
>      }
I think we can remove `private List<String> items;` because your passenger already has luggage with items

2023-04-26 09:51 UTC, ankochergin commented on src/com/airport/RunwayStatus.java
> +}
```suggestion
public enum RunwayStatus {
    IDLE,
    TAKEOFF,
    LANDING
}
```

2023-04-26 09:51 UTC, ankochergin commented on src/com/airport/SFORoute.java
> +}
create just Route class and set origin and destination using setters
then your Flight should contain Route field

2023-04-26 09:51 UTC, ankochergin commented on src/com/impl/airport/AirportTicketCounter.java
> -
empty line should be between methods

2023-04-26 09:51 UTC, ankochergin commented on src/com/impl/airport/AirportTicketCounter.java
> +}
```suggestion
    }\
    
}
```

2023-04-26 09:51 UTC, ankochergin commented on src/com/impl/airport/EmiratesAirlines.java
> +    }
```suggestion
    static{
        Printer.print("Have a Nice and Happy Journey with Emirates Airlines");
    }
```

2023-04-26 09:51 UTC, ankochergin commented on src/com/impl/airport/EmiratesAirlines.java
> +    }
make method void and rename to printAvailableDiscount since you just return 0

2023-04-26 09:51 UTC, ankochergin commented on src/com/impl/airport/EmiratesAirlines.java
> +    }
same formatting issue in all classes

2023-04-26 09:51 UTC, ankochergin commented on src/com/impl/airport/route/SingaporeRoute.java
> +public class SingaporeRoute implements Route {
please check comment above about Route class
We shouldn't create different classes with the same code, we should have one Route and set different origin and destinations
remove these classes

2023-04-26 09:51 UTC, ankochergin commented on src/com/impl/airport/UnitedAirlines.java
> +public class UnitedAirlines extends Flight {
the same here (please check comments about Route)
we can have 1 Flight class with different company names, routes, prices, food which are set using setters or constructor. please remove these classes

2023-04-26 09:51 UTC, ankochergin commented on src/com/person/Designation.java
> +    MANAGER;
```suggestion
public enum Designation {
    PILOT,
    AIRHOSTESS,
    CARGO_MANAGER,
    CUSTOMERCARE,
    MANAGER;
```

2023-04-27 04:46 UTC, chindhur commented on src/com/airport/Airport.java
> +    private Boolean IsRunwayOPen = true;
changed the variable name

2023-04-27 04:47 UTC, chindhur commented on src/com/airport/Flight.java
> +    }
corrected the above change in all classes.

2023-04-27 04:50 UTC, chindhur commented on src/com/airport/Passenger.java
>      }
Changed the passenger items to cabinItems, and the items at luggage as checkinItems. Hope its fine now.

2023-04-27 04:50 UTC, chindhur commented on src/com/airport/RunwayStatus.java
> +}
corrected the space.

2023-04-27 04:51 UTC, chindhur commented on src/com/impl/airport/EmiratesAirlines.java
> +    }
corrected the above change in all classes.

2023-04-27 04:52 UTC, chindhur commented on src/com/impl/airport/route/SingaporeRoute.java
> +public class SingaporeRoute implements Route {
deleted.

2023-04-27 05:46 UTC, chindhur commented on src/com/impl/airport/UnitedAirlines.java
> +public class UnitedAirlines extends Flight {
Initially I had created Flight as concrete class, but as the homework asked for an abstract classes to be implemented , I converted this to abstract class. If i convert the above way , I will not have an abstract class. Please let me know your suggestion.

2023-04-27 05:52 UTC, chindhur commented on src/com/impl/airport/UnitedAirlines.java
> +public class UnitedAirlines extends Flight {
Also implemented polymophism on printDiscount, getWelcomeMessage, getSeatCapacity methods in EmiratesAirlines,SouthwestAirlines,SingaporeAirlines and united Airlines classes. So removing these classes will take out polymorphism as well.

2023-04-27 10:02 UTC, ankochergin commented on src/com/airport/AirportRunway.java
> +        if (isRunwayOccupied == true) {
if we want check boolean in if we can just write if (isRunwayOccupied)

2023-04-27 10:02 UTC, ankochergin commented on src/com/airport/Main.java
> +        List<FoodMenu> menuList = null;
please declare variable when you use it

2023-04-27 10:02 UTC, ankochergin commented on src/com/impl/airport/AirportTicketCounter.java
> +public class AirportTicketCounter implements ITicketCounter {
I just noticed that this TicketCounter class stores info about only 1 ticket. I think ticket counter should provide you an ability to bookTicket using Passenger and Flight arguments
and this method should return you ticket

2023-04-27 10:02 UTC, ankochergin commented on src/com/impl/airport/AirportTicketCounter.java
> +public class AirportTicketCounter implements ITicketCounter {
also your TicketCounter should store list of all booked tickets

2023-04-27 10:02 UTC, ankochergin commented on src/com/impl/airport/UnitedAirlines.java
> +public class UnitedAirlines extends Flight {
Please think about other places where you can you polymorphism and an abstract class

2023-04-27 10:02 UTC, ankochergin commented on src/com/airport/Flight.java
> +    private static Integer noOfWings;
I think your flight should have Route

2023-05-01 10:54 UTC, ankochergin commented on src/com/airport/Airport.java
> +    }
```suggestion
    public void setRunwayOpen(Boolean isRunwayOpen) {
        isRunwayOpen = isRunwayOpen;
    }
```

2023-05-01 10:54 UTC, ankochergin commented on src/com/airport/Airport.java
> +    }
you already have Flight class, flightId and flightName are already there

2023-05-01 10:54 UTC, ankochergin commented on src/com/airport/Airport.java
> +        airplaneEmployeeList.add(airplaneEmployee);
```suggestion
    public void addAirplaneEmployee(AirplaneEmployee airplaneEmployee) {
        airplaneEmployeeList.add(airplaneEmployee);
```

2023-05-01 10:54 UTC, ankochergin commented on src/com/airport/Airport.java
> +        airportEmployeeList.add(airportEmployee);
```suggestion
    public void addAirportEmployee(AirportEmployee airportEmployee) {
        airportEmployeeList.add(airportEmployee);
```

2023-05-01 10:54 UTC, ankochergin commented on src/com/airport/Flight.java
> +    throws NoSeatLeftException{
```suggestion
    public int bookASeat() throws NoSeatLeftException{
```

2023-05-01 10:54 UTC, ankochergin commented on src/com/airport/Main.java
> +        Printer.print("---------------------------");
```suggestion
    public static void main(String[] args) {
        Printer.print("---------------------------");
```

2023-05-01 10:54 UTC, ankochergin commented on src/com/impl/airport/Luggage.java
>      private String flightId;
you already have it in the Flight

2023-05-01 10:54 UTC, ankochergin commented on src/com/impl/airport/Luggage.java
>      private String passengerId;
Already exists in Passenger

2023-05-01 10:54 UTC, ankochergin commented on src/com/impl/airport/Luggage.java
> +    }
maybe addLuggage should be in Passenger? Because luggage cannot addLuggage to itself

2023-05-01 10:54 UTC, ankochergin commented on src/com/airport/Ticket.java
> +    }
variable names should never start with uppercase letter unless it's constant

2023-05-01 10:54 UTC, ankochergin commented on src/com/logs/SolvdAirport.log
> +[INFO ] 2023-04-30 21:38:24.030 [main] Printer - AIRPORT: ---------------------------
remove log file from git

2023-05-01 10:54 UTC, ankochergin commented on src/com/person/Employee.java
> +import com.Exception.InvalidEmployeeIdException;
check java naming conventions for packages

2023-05-01 10:54 UTC, ankochergin commented on src/com/utils/Printer.java
> +    private static Logger logger = LogManager.getLogger(Printer.class);
logger should be final

2023-05-02 11:08 UTC, ankochergin commented on src/com/airport/Airport.java
> +    }
why do we need this Map? It looks like code duplication, we already have flightID and flightName in Flight, but you're duplication this String in Map

2023-05-02 11:08 UTC, ankochergin commented on src/com/airport/AirportEmployee.java
> +        return airportName;
Airport class already has airportName and list of all employees, I don't think that we should duplicate airportName data here

2023-05-02 11:08 UTC, ankochergin commented on src/com/impl/airport/AirportTicketCounter.java
> +    }
When we book a ticket at a counter we don't have ticket yet, I think you should enter all information here, you should have ticket as an argument
we should have ticket as an argument only in we are trying to modify of or cancel at a counter

2023-05-02 11:08 UTC, ankochergin commented on src/com/impl/airport/Luggage.java
>      private String flightId;
not fixed

2023-05-02 11:08 UTC, ankochergin commented on src/com/impl/airport/Luggage.java
>      private String passengerId;
not fixed

2023-05-02 11:08 UTC, ankochergin commented on src/com/impl/airport/Passenger.java
> +
why Passenger has Person passenger as an field? I think your class should extend Passenger

2023-05-03 04:25 UTC, chindhur commented on src/com/airport/Airport.java
> +    }
updated Airlines map to get the flight details from flight ID

2023-05-03 04:25 UTC, chindhur commented on src/com/airport/AirportEmployee.java
> +        return airportName;
removed airport name duplication.

2023-05-03 04:26 UTC, chindhur commented on src/com/impl/airport/AirportTicketCounter.java
> +    }
changed as per review.

2023-05-03 04:29 UTC, chindhur commented on src/com/impl/airport/Passenger.java
> +
removed passenger field.
 Also am not able to find MAX_ALLOWED_LUGGAGE field in my code. I think it got missed in last push. Could you please check now.

2023-05-03 16:13 UTC, ankochergin commented on src/com/airport/Airport.java
I'm not sure that Map is good to use here, I don't see a reason to store flightId as key and flightId in Flight. I think regular ArrayList would be better here

2023-05-03 16:13 UTC, ankochergin commented on src/com/airport/Main.java
> +        Printer.print("Please enter the airport name: ");
```suggestion
    public static void checkAirport(Airport airport) throws NotFoundException {
        Scanner sc = new Scanner(System.in);
        Printer.print("Please enter the airport name: ");
```

2023-05-03 16:13 UTC, ankochergin commented on src/com/airport/Main.java
> +    }
```suggestion
    public static void checkAirlines(Airport airport) throws NotFoundException {
        Scanner sc = new Scanner(System.in);
        Printer.print("Please enter the airline flight identifier for searching food menu: ");
        String name = sc.nextLine();
        Printer.print("searching airline:"+ name);
        if (airport.getAirlines(name) != null) {
            airport.getAirlines(name).printDetails();
        }
        else {
            throw new NotFoundException(name + " : Airline not found!");
        }
    }
```

2023-05-03 17:28 UTC, chindhur commented on src/com/airport/Airport.java
changed map to list

2023-05-04 16:27 UTC, merged